package cli

import (
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/fiddler110/aegis/internal/config"
	"github.com/spf13/cobra"
	yamlv3 "go.yaml.in/yaml/v3"
)

// ─── Shared addition content ───────────────────────────────────────────────
//
// New template content is written once here and spliced into
// globalConfigTemplateRaw (for fresh --first-init) AND into configAdditions
// below (for `aegis config update` against a config file created by an
// older version), so the two paths never drift apart. The project
// template's own copy is illustrative-only static text (see
// projectConfigTemplateRaw) since it lives inside an already-commented
// example block there, not a live section — it isn't wired through this
// shared const.
//
// Every addition is wrapped in a "aegis:added <id>"/"aegis:end <id>" marker
// comment pair. The marker text is what makes `config update` idempotent
// (skip if already present) — never reuse an id for a different meaning
// once it has shipped.
//
// The block always assumes it's being spliced as a sibling of other 2-space-
// indented, single-`#`-commented fields directly under an ACTIVE top-level
// key (e.g. a real `security:` mapping) — that's the only case `config
// update` ever auto-splices into (see insertIntoSection).

const securityScannerConfigID = "security-scanner-config"

const securityScannerAdditionBlock = `  # ── Per-scanner config for ` + "`aegis scan`" + ` / the security_scan tool ──────────
  # aegis:added security-scanner-config
  # default_method: auto        # host | container | auto (fallback default)
  # wsl_distro: kali-linux      # Windows only: target this WSL distro for nmap/nuclei/
  #                             # opengrep/kubescape (P14.x) instead of the WSL default —
  #                             # recommended for red-team/recon work (see docs/security.md)
  # tools:                      # keyed by scanner name (aegis scan --list)
  #   semgrep:    { enabled: true, method: host }
  #   trivy:      { enabled: true, image: "trivy@sha256:..." }
  #   gitleaks:   { enabled: true }
  #   trufflehog: { enabled: true, verify: false }   # live credential check, host-only
  #   nmap:       { method: wsl }                    # force WSL over a flaky native Windows install
  #   nuclei:     { method: wsl, templates_version: "v9.62.0" }
  # dast:                       # dast_scan target-authorization policy
  #   allowed_targets: []       # hostnames/".suffix" wildcards/CIDRs
  #   allow_active: false       # opt-in for active/api scan modes
  # debate:                     # route findings through a P12 debate round
  #   threat_model: false
  #   triage: false
  # aegis:end security-scanner-config`

// configAddition is one incremental piece of template content that a config
// file generated by an older version of Aegis may be missing.
type configAddition struct {
	id         string // marker id — never reused once shipped
	sectionKey string // top-level YAML key this extends, e.g. "security"
	block      string // 2-space-indented, commented block to splice in
}

// configAdditions lists every incremental addition `aegis config update`
// knows how to reconcile. Append to this list (never edit an existing
// entry's id) whenever SecurityConfig or another top-level section grows a
// field the templates don't yet document.
var configAdditions = []configAddition{
	{
		id:         securityScannerConfigID,
		sectionKey: "security",
		block:      securityScannerAdditionBlock,
	},
}

// updateConfigFile reconciles a single existing config file against
// configAdditions, extending only sections that already exist as an active,
// uncommented top-level key, and only with content not already present
// (detected via the "aegis:added <id>" marker). It never touches anything
// else in the file — no reformatting, no rewriting of existing keys — and
// refuses to write if the result doesn't parse as valid YAML.
//
// When a section isn't active in the file (missing entirely, or still only
// a commented-out example), the addition is not guessed at — it's reported
// so the user can add it by hand, since splicing into a comment-only example
// block reliably is a much harder text-matching problem than extending a
// real mapping, and guessing wrong risks a confusing result.
func updateConfigFile(path string, dryRun bool) (report []string, changed bool, err error) {
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return []string{fmt.Sprintf("%s: not found, nothing to update (run --first-init/--init first)", path)}, false, nil
	}
	if err != nil {
		return nil, false, err
	}

	hasCRLF := strings.Contains(string(raw), "\r\n")
	text := strings.ReplaceAll(string(raw), "\r\n", "\n")

	var applied []string
	for _, add := range configAdditions {
		marker := "aegis:added " + add.id
		if strings.Contains(text, marker) {
			continue // already applied in an earlier run
		}
		newText, ok := insertIntoSection(text, add.sectionKey, add.block)
		if !ok {
			report = append(report, fmt.Sprintf(
				"%s: no active %q section found to extend — add this manually (inside a `%s:` mapping):\n%s",
				path, add.sectionKey, add.sectionKey, add.block))
			continue
		}
		text = newText
		applied = append(applied, add.id)
	}

	if len(applied) == 0 {
		return report, false, nil
	}

	// Safety net: never write a file that no longer parses as YAML, no
	// matter how confident the text-splice logic above was.
	var probe map[string]any
	if err := yamlv3.Unmarshal([]byte(text), &probe); err != nil {
		return nil, false, fmt.Errorf("update to %s would produce invalid YAML, aborting without writing: %w", path, err)
	}

	out := text
	if hasCRLF {
		out = strings.ReplaceAll(out, "\n", "\r\n")
	}

	if dryRun {
		report = append([]string{fmt.Sprintf("%s: would add %s (dry run, not written)", path, strings.Join(applied, ", "))}, report...)
		return report, true, nil
	}

	backup := fmt.Sprintf("%s.bak-%d", path, time.Now().Unix())
	if err := os.WriteFile(backup, raw, 0o600); err != nil {
		return nil, false, fmt.Errorf("write backup %s: %w", backup, err)
	}
	if err := os.WriteFile(path, []byte(out), 0o600); err != nil {
		return nil, false, fmt.Errorf("write %s: %w", path, err)
	}
	report = append([]string{fmt.Sprintf("%s: added %s (backup saved to %s)", path, strings.Join(applied, ", "), backup)}, report...)
	return report, true, nil
}

// insertIntoSection finds the top-level (column-0), active "<key>:" line in
// text and splices block in just before the section ends — the first
// subsequent line that itself starts at column 0 (the next top-level key or
// a banner comment), or EOF if the section runs to the end of the file.
// Every line belonging to a section in these templates is blank or indented,
// so a column-0, non-blank line reliably marks the boundary. Returns
// ok=false without modifying text if no active "<key>:" line is found (this
// intentionally does not match a commented-out "# <key>:" example line —
// see the doc comment on updateConfigFile).
func insertIntoSection(text, key, block string) (string, bool) {
	startRe := regexp.MustCompile(`(?m)^` + regexp.QuoteMeta(key) + `:[ \t]*(#.*)?$`)
	loc := startRe.FindStringIndex(text)
	if loc == nil {
		return "", false
	}
	rest := text[loc[1]:]
	boundaryRe := regexp.MustCompile(`(?m)^\S`)
	insertPos := len(text)
	if b := boundaryRe.FindStringIndex(rest); b != nil {
		insertPos = loc[1] + b[0]
	}
	head := strings.TrimRight(text[:insertPos], "\n")
	tail := text[insertPos:]
	if tail == "" {
		return head + "\n" + block + "\n", true
	}
	return head + "\n" + block + "\n\n" + tail, true
}

func newConfigUpdateCmd() *cobra.Command {
	var (
		global  bool
		project bool
		dryRun  bool
	)
	c := &cobra.Command{
		Use:   "update",
		Short: "Reconcile an existing config file with newer template content, without discarding customizations",
		Long: `Merges template content added to Aegis since a config file was created
(e.g. new security-scanner options) into that existing file. Existing keys,
comments, and formatting are left untouched — only genuinely new, previously
absent content is spliced in, and only into a section you're already using
(an active top-level key). A backup of the original is written alongside it
before any change.

With no flags, both the global config (` + config.GlobalConfigPath() + `) and the
project config (./` + config.ProjectConfigPath() + `) are reconciled if they exist.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if !global && !project {
				global, project = true, true
			}
			var anyChanged bool
			if global {
				report, changed, err := updateConfigFile(config.GlobalConfigPath(), dryRun)
				if err != nil {
					return err
				}
				for _, line := range report {
					fmt.Fprintln(cmd.OutOrStdout(), line)
				}
				anyChanged = anyChanged || changed
			}
			if project {
				report, changed, err := updateConfigFile(config.ProjectConfigPath(), dryRun)
				if err != nil {
					return err
				}
				for _, line := range report {
					fmt.Fprintln(cmd.OutOrStdout(), line)
				}
				anyChanged = anyChanged || changed
			}
			if !anyChanged {
				fmt.Fprintln(cmd.OutOrStdout(), "nothing to update")
			}
			return nil
		},
	}
	c.Flags().BoolVar(&global, "global", false, "only reconcile the global config")
	c.Flags().BoolVar(&project, "project", false, "only reconcile the project config")
	c.Flags().BoolVar(&dryRun, "dry-run", false, "show what would change without writing")
	return c
}
