package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/scottymacleod/aegis/internal/config"
)

// runFirstInit writes the global config template to the user's OS config
// directory. It aborts if the file already exists to avoid clobbering changes.
func runFirstInit() error {
	path := config.GlobalConfigPath()
	return writeConfigTemplate(path, globalConfigTemplate, "global")
}

// runProjectInit writes a project-level override template to .aegis/config.yaml
// in the current working directory. It aborts if the file already exists.
func runProjectInit() error {
	path := config.ProjectConfigPath()
	return writeConfigTemplate(path, projectConfigTemplate, "project")
}

func writeConfigTemplate(path, template, label string) error {
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("%s config already exists at %s\nEdit it directly or delete it and re-run to regenerate.", label, path)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create config directory: %w", err)
	}
	if err := os.WriteFile(path, []byte(template), 0o600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	fmt.Printf("Created %s config: %s\n", label, path)
	return nil
}

// ─── Global config template ───────────────────────────────────────────────────

const globalConfigTemplate = `# ═══════════════════════════════════════════════════════════════════════════════
# Aegis  ·  Global Configuration
# Generated by: aegis --first-init
#
# Precedence (highest wins):
#   environment variables  >  project config (.aegis/config.yaml)  >  this file
#
# API keys are NEVER read from this file — always set them as environment
# variables so they are not accidentally committed to source control.
# ═══════════════════════════════════════════════════════════════════════════════


# ┌─────────────────────────────────────────────────────────────────────────────
# │  PROVIDER  ·  ACTIVE: Ollama  (local, no API key required by the model)
# └─────────────────────────────────────────────────────────────────────────────
#
# Ollama uses the OpenAI-compatible adapter. The harness still reads
# OPENAI_API_KEY to authenticate the HTTP request, but Ollama accepts any
# non-empty value. Set a dummy value once so the harness does not refuse to
# start:
#
#   Windows PowerShell:   $env:OPENAI_API_KEY = "ollama"
#   Windows (permanent):  Add to: System → Advanced → Environment Variables
#   macOS / Linux:        export OPENAI_API_KEY=ollama    (add to ~/.zshrc etc.)
#
# Ollama is started automatically if it is installed but not yet running.
# Model library:       https://ollama.com/library
#
provider:
  default: openai
  base_url: "http://localhost:11434/v1"
  model: "auto"              # "auto" picks the first available Ollama model
                             # automatically. Or pin a model you have pulled:
                             #   llama3.2, mistral, gemma3, qwen2.5, phi4, etc.
  max_tokens: 8192           # Adjust to fit your model's context window.
  max_retries: 3
  think: false               # true only for extended-thinking models such as
                             #   qwen3 or deepseek-r1 served via Ollama.


# ┌─────────────────────────────────────────────────────────────────────────────
# │  PROVIDER  ·  Anthropic  (Claude)          — uncomment to activate
# └─────────────────────────────────────────────────────────────────────────────
# Requires:  export ANTHROPIC_API_KEY=sk-ant-...
# Keys at:   https://console.anthropic.com/settings/keys
#
# provider:
#   default: anthropic
#   model: "claude-opus-4-8"   # claude-opus-4-8  |  claude-sonnet-4-6
#                              # claude-haiku-4-5-20251001
#   max_tokens: 16384
#   max_retries: 4
#   think: ~                   # ~ = provider default; false = disable thinking
#   # base_url: ""             # Override only when using a proxy / gateway.
#   # headers:                 # Extra headers for gateway auth, e.g.:
#   #   x-gateway-key: "token"


# ┌─────────────────────────────────────────────────────────────────────────────
# │  PROVIDER  ·  OpenAI                        — uncomment to activate
# └─────────────────────────────────────────────────────────────────────────────
# Requires:  export OPENAI_API_KEY=sk-...
# Keys at:   https://platform.openai.com/api-keys
#
# provider:
#   default: openai
#   model: "gpt-4o"            # gpt-4o  |  gpt-4o-mini  |  gpt-4-turbo
#                              # o1  |  o1-mini  |  o3  |  o3-mini
#   max_tokens: 16384
#   max_retries: 4
#   think: ~


# ┌─────────────────────────────────────────────────────────────────────────────
# │  PROVIDER  ·  Azure OpenAI                  — uncomment to activate
# └─────────────────────────────────────────────────────────────────────────────
# Requires:  export OPENAI_API_KEY=<your-azure-api-key>
# Replace <resource> and <deployment> with your Azure deployment details.
#
# provider:
#   default: openai
#   base_url: "https://<resource>.openai.azure.com/openai/deployments/<deployment>"
#   model: "gpt-4o"
#   max_tokens: 16384
#   max_retries: 4
#   headers:
#     api-version: "2024-05-01-preview"


# ┌─────────────────────────────────────────────────────────────────────────────
# │  PROVIDER  ·  Groq  (fast cloud inference)  — uncomment to activate
# └─────────────────────────────────────────────────────────────────────────────
# Requires:  export OPENAI_API_KEY=gsk_...
# Keys at:   https://console.groq.com/keys
#
# provider:
#   default: openai
#   base_url: "https://api.groq.com/openai/v1"
#   model: "llama-3.3-70b-versatile"
#                              # llama-3.3-70b-versatile  |  llama-3.1-8b-instant
#                              # mixtral-8x7b-32768  |  gemma2-9b-it
#   max_tokens: 8192
#   max_retries: 4
#   think: false


# ┌─────────────────────────────────────────────────────────────────────────────
# │  PROVIDER  ·  OpenRouter  (unified gateway)  — uncomment to activate
# └─────────────────────────────────────────────────────────────────────────────
# Requires:  export OPENAI_API_KEY=sk-or-...
# Keys at:   https://openrouter.ai/settings/keys
# Model list: https://openrouter.ai/models
#
# provider:
#   default: openai
#   base_url: "https://openrouter.ai/api/v1"
#   model: "anthropic/claude-opus-4"
#   max_tokens: 16384
#   max_retries: 4
#   headers:
#     HTTP-Referer: "https://github.com/fiddler110/Aegis"
#     X-Title: "Aegis"


# ┌─────────────────────────────────────────────────────────────────────────────
# │  PROVIDER  ·  LM Studio  (local)            — uncomment to activate
# └─────────────────────────────────────────────────────────────────────────────
# Requires:  export OPENAI_API_KEY=lmstudio
# Enable:    LM Studio → Settings → Local Server → Start Server
#
# provider:
#   default: openai
#   base_url: "http://localhost:1234/v1"
#   model: "local-model"       # Use the identifier shown in LM Studio's model list.
#   max_tokens: 4096
#   max_retries: 2
#   think: false


# ┌─────────────────────────────────────────────────────────────────────────────
# │  PROVIDER  ·  Google Vertex AI              — uncomment to activate
# └─────────────────────────────────────────────────────────────────────────────
# Requires:  export OPENAI_API_KEY=<vertex-api-key-or-bearer-token>
# Replace <project>, <region>, and <model-id> with your Vertex details.
#
# provider:
#   default: openai
#   base_url: "https://<region>-aiplatform.googleapis.com/v1beta1/projects/<project>/locations/<region>/endpoints/openapi"
#   model: "google/gemini-2.0-flash-001"
#   max_tokens: 8192
#   max_retries: 4


# ─────────────────────────────────────────────────────────────────────────────
#  Permission & behaviour
# ─────────────────────────────────────────────────────────────────────────────

permission:
  mode: build                # "plan" = read-only (safe default for untrusted dirs)
                             # "build" = file edits allowed; shell requires approval
  auto_approve_exec: false   # true = never prompt for shell/execute tool calls


# ─────────────────────────────────────────────────────────────────────────────
#  Spend guard  (cloud providers only — Ollama has no cost)
# ─────────────────────────────────────────────────────────────────────────────

cost:
  budget_usd: 0.0            # 0 = unlimited. Set e.g. 5.0 to abort past $5.00.


# ─────────────────────────────────────────────────────────────────────────────
#  Daemon address
# ─────────────────────────────────────────────────────────────────────────────

server:
  addr: "127.0.0.1:4127"    # Change the port if 4127 is already in use.


# ─────────────────────────────────────────────────────────────────────────────
#  Logging
# ─────────────────────────────────────────────────────────────────────────────

log_level: info              # debug | info | warn | error


# ─────────────────────────────────────────────────────────────────────────────
#  Diagrams  (render_diagram tool)
# ─────────────────────────────────────────────────────────────────────────────

diagram:
  kroki_url: "https://kroki.io"
  # Self-host Kroki for air-gapped environments:
  # https://docs.kroki.io/kroki/setup/install/


# ─────────────────────────────────────────────────────────────────────────────
#  Multi-agent / swarm
# ─────────────────────────────────────────────────────────────────────────────

swarm:
  backend: in_process        # "in_process"  = goroutines, low overhead (default)
                             # "subprocess"  = process-isolated workers


# ─────────────────────────────────────────────────────────────────────────────
#  Shell execution sandbox
# ─────────────────────────────────────────────────────────────────────────────

sandbox:
  backend: local             # "local"     = run commands directly on the host
                             # "container" = isolate each command in Docker/Podman
  # image: ubuntu:22.04      # Container image when backend=container.
  # network: false           # Allow outbound network inside containers?


# ─────────────────────────────────────────────────────────────────────────────
#  Security policies
# ─────────────────────────────────────────────────────────────────────────────

security:
  egress_then_write: false   # true = require explicit approval for any file write
                             # that follows a network call in the same session.
  # network_allowlist:       # Restrict web_fetch / web_search to these domains.
  #   - "github.com"         # Empty list = no restriction (default).
  #   - "docs.python.org"
  #   - "pkg.go.dev"


# ─────────────────────────────────────────────────────────────────────────────
#  LSP servers  (code intelligence — diagnostics, go-to-definition, etc.)
# ─────────────────────────────────────────────────────────────────────────────

# lsp:
#   - name: gopls
#     command: gopls
#     args: []
#     extensions: [".go"]
#
#   - name: pyright
#     command: pyright-langserver
#     args: ["--stdio"]
#     extensions: [".py"]
#
#   - name: rust-analyzer
#     command: rust-analyzer
#     args: []
#     extensions: [".rs"]
#
#   - name: typescript-language-server
#     command: typescript-language-server
#     args: ["--stdio"]
#     extensions: [".ts", ".tsx", ".js", ".jsx"]
#
#   - name: clangd
#     command: clangd
#     args: []
#     extensions: [".c", ".cpp", ".h", ".hpp"]


# ─────────────────────────────────────────────────────────────────────────────
#  MCP servers  (external tool servers via the Model Context Protocol)
# ─────────────────────────────────────────────────────────────────────────────

# mcp:
#   - name: filesystem
#     command: npx
#     args: ["-y", "@modelcontextprotocol/server-filesystem", "/home/user/projects"]
#
#   - name: github
#     command: npx
#     args: ["-y", "@modelcontextprotocol/server-github"]
#     env:
#       GITHUB_PERSONAL_ACCESS_TOKEN: "ghp_..."
#
#   - name: postgres
#     command: npx
#     args: ["-y", "@modelcontextprotocol/server-postgres", "postgresql://localhost/mydb"]
#
#   - name: brave-search
#     command: npx
#     args: ["-y", "@modelcontextprotocol/server-brave-search"]
#     env:
#       BRAVE_API_KEY: "BSA..."


# ─────────────────────────────────────────────────────────────────────────────
#  Process plugins  (external executables exposed as tools)
# ─────────────────────────────────────────────────────────────────────────────

# plugins:
#   - name: my_tool
#     description: "Run my custom analysis script"
#     command: python
#     args: ["/path/to/script.py"]
#     capability: execute        # read | write | execute | network
#     timeout_sec: 30
#     input_schema: >
#       {"type":"object","properties":{"target":{"type":"string"}},"required":["target"]}
`

// ─── Project config template ──────────────────────────────────────────────────

const projectConfigTemplate = `# ═══════════════════════════════════════════════════════════════════════════════
# Aegis  ·  Project Configuration
# Generated by: aegis --init
#
# This file overrides your global config (~/.config/aegis/config.yaml) for
# THIS PROJECT ONLY. Commit it to share settings with your team — it contains
# no secrets (API keys always come from environment variables).
#
# Precedence: environment variables  >  this file  >  global config
# ═══════════════════════════════════════════════════════════════════════════════

# ── Override the model for this project ──────────────────────────────────────
# Useful when a project needs a specific capability (e.g. a reasoning model
# for security analysis, or a fast small model for routine edits).
# For Ollama, "auto" selects the first available model automatically.
#
# provider:
#   model: "auto"              # Ollama: pick the first available model
#   # model: "qwen3:32b"       # pin a specific Ollama model
#   # model: "claude-opus-4-8" # Anthropic example
#   # max_tokens: 32768


# ── Tighten the permission posture for sensitive repos ────────────────────────
#
# permission:
#   mode: plan                 # Read-only: no file writes or shell commands.
#   auto_approve_exec: false


# ── Cap spending for this project ─────────────────────────────────────────────
#
# cost:
#   budget_usd: 2.0            # Abort if estimated cost exceeds $2.00.


# ── Restrict network access to project-relevant domains ───────────────────────
#
# security:
#   network_allowlist:
#     - "github.com"
#     - "pkg.go.dev"
#     - "docs.python.org"


# ── Project-specific LSP servers ─────────────────────────────────────────────
#
# lsp:
#   - name: gopls
#     command: gopls
#     args: []
#     extensions: [".go"]


# ── Project-specific MCP servers ─────────────────────────────────────────────
#
# mcp:
#   - name: github
#     command: npx
#     args: ["-y", "@modelcontextprotocol/server-github"]
#     env:
#       GITHUB_PERSONAL_ACCESS_TOKEN: "ghp_..."


# ── Notes ─────────────────────────────────────────────────────────────────────
# Files you should NOT commit from .aegis/:
#   .aegis/sessions.db     — local session history
#   .aegis/daemon.token    — auth token for the local daemon
#   .aegis/aegis.log       — daemon log
#
# Add these lines to your .gitignore if they are not already covered:
#   .aegis/sessions.db
#   .aegis/daemon.token
#   .aegis/*.log
`
